data=`[
    {
      "latin": "Andromeda",
      "english": "Princess of Ethiopia",
      "objectType": "Human",
      "area": 722.278,
      "mainStars": 16,
      "ra": "00h 08m 23.17s",
      "raHour": 0,
      "raMinute": 8,
      "raSecond": 23.17,
      "declination": "29° 05′ 27.0″",
      "declinationDegree": 29,
      "declinationMinute": 5,
      "declinationSecond": 27,
      "starColor": "Blue"
    },
    {
      "latin": "Antlia",
      "english": "Air pump",
      "objectType": "Inanimate",
      "area": 238.901,
      "mainStars": 3,
      "ra": "10h 27m 09.16s",
      "raHour": 10,
      "raMinute": 27,
      "raSecond": 9.16,
      "declination": "−31° 04′ 04.1″",
      "declinationDegree": -31,
      "declinationMinute": 4,
      "declinationSecond": 4.1,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Apus",
      "english": "Bird of Paradise",
      "objectType": "Animal",
      "area": 206.327,
      "mainStars": 4,
      "ra": "14h 47m 51.73s",
      "raHour": 14,
      "raMinute": 47,
      "raSecond": 51.73,
      "declination": "−79° 02′ 41.0″",
      "declinationDegree": -79,
      "declinationMinute": 2,
      "declinationSecond": 41,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Aquarius",
      "english": "Water bearer",
      "objectType": "Human",
      "area": 979.854,
      "mainStars": 10,
      "ra": "21h 31m 33.52s",
      "raHour": 21,
      "raMinute": 31,
      "raSecond": 33.52,
      "declination": "−05° 34′ 16.2″",
      "declinationDegree": -5,
      "declinationMinute": 34,
      "declinationSecond": 16.2,
      "starColor": "Yellow"
    },
    {
      "latin": "Aquila",
      "english": "Eagle",
      "objectType": "Animal",
      "area": 652.473,
      "mainStars": 10,
      "ra": "19h 50m 46.68s",
      "raHour": 19,
      "raMinute": 50,
      "raSecond": 46.68,
      "declination": "08° 52′ 02.6″",
      "declinationDegree": 8,
      "declinationMinute": 52,
      "declinationSecond": 2.6,
      "starColor": "White"
    },
    {
      "latin": "Ara",
      "english": "Altar",
      "objectType": "Inanimate",
      "area": 237.057,
      "mainStars": 8,
      "ra": "17h 25m 18.00s",
      "raHour": 17,
      "raMinute": 25,
      "raSecond": 18,
      "declination": "−55° 31′ 47.4″",
      "declinationDegree": -55,
      "declinationMinute": 31,
      "declinationSecond": 47.4,
      "starColor": "Blue"
    },
    {
      "latin": "Aries",
      "english": "Ram",
      "objectType": "Animal",
      "area": 441.395,
      "mainStars": 4,
      "ra": "02h 07m 10.29s",
      "raHour": 2,
      "raMinute": 7,
      "raSecond": 10.29,
      "declination": "23° 27′ 46.0″",
      "declinationDegree": 23,
      "declinationMinute": 27,
      "declinationSecond": 46,
      "starColor": "Red"
    },
    {
      "latin": "Auriga",
      "english": "Charioteer",
      "objectType": "Human",
      "area": 657.438,
      "mainStars": 5,
      "ra": "05h 16m 41.30s",
      "raHour": 5,
      "raMinute": 16,
      "raSecond": 41.3,
      "declination": "45° 59′ 56.5″",
      "declinationDegree": 45,
      "declinationMinute": 59,
      "declinationSecond": 56.5,
      "starColor": "Yellow"
    },
    {
      "latin": "Bootes",
      "english": "Herdsman",
      "objectType": "Human",
      "area": 906.831,
      "mainStars": 7,
      "ra": "14h 15m 40.35s",
      "raHour": 14,
      "raMinute": 15,
      "raSecond": 40.35,
      "declination": "19° 11′ 14.2″",
      "declinationDegree": 19,
      "declinationMinute": 11,
      "declinationSecond": 14.2,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Caelum",
      "english": "Graving tool",
      "objectType": "Inanimate",
      "area": 124.865,
      "mainStars": 4,
      "ra": "04h 40m 33.82s",
      "raHour": 4,
      "raMinute": 40,
      "raSecond": 33.82,
      "declination": "−41° 51′ 48.9″",
      "declinationDegree": -41,
      "declinationMinute": 51,
      "declinationSecond": 48.9,
      "starColor": "Yellow"
    },
    {
      "latin": "Camelopardus",
      "english": "Giraffe",
      "objectType": "Animal",
      "area": 756.828,
      "mainStars": 8,
      "ra": "05h 03m 25.10s",
      "raHour": 5,
      "raMinute": 3,
      "raSecond": 25.1,
      "declination": "60° 26′ 32.2″",
      "declinationDegree": 60,
      "declinationMinute": 26,
      "declinationSecond": 32.2,
      "starColor": "Yellow"
    },
    {
      "latin": "Cancer",
      "english": "Crab",
      "objectType": "Animal",
      "area": 505.872,
      "mainStars": 5,
      "ra": "08h 16m 30.95s",
      "raHour": 8,
      "raMinute": 16,
      "raSecond": 30.95,
      "declination": "09° 11′ 08.4″",
      "declinationDegree": 9,
      "declinationMinute": 11,
      "declinationSecond": 8.4,
      "starColor": "Red"
    },
    {
      "latin": "Canes Venatici",
      "english": "Hunting dogs",
      "objectType": "Animal",
      "area": 465.194,
      "mainStars": 2,
      "ra": "12h 56m 01.84s",
      "raHour": 12,
      "raMinute": 56,
      "raSecond": 1.84,
      "declination": "38° 19′ 05.7″",
      "declinationDegree": 38,
      "declinationMinute": 19,
      "declinationSecond": 5.7,
      "starColor": "White"
    },
    {
      "latin": "Canis Major",
      "english": "Big dog",
      "objectType": "Animal",
      "area": 380.118,
      "mainStars": 8,
      "ra": "06h 45m 09.25s",
      "raHour": 6,
      "raMinute": 45,
      "raSecond": 9.25,
      "declination": "−16° 42′ 47.3″",
      "declinationDegree": -16,
      "declinationMinute": 42,
      "declinationSecond": 47.3,
      "starColor": "Blue"
    },
    {
      "latin": "Canis Minor",
      "english": "Little dog",
      "objectType": "Animal",
      "area": 183.367,
      "mainStars": 2,
      "ra": "07h 39m 18.54s",
      "raHour": 7,
      "raMinute": 39,
      "raSecond": 18.54,
      "declination": "05° 13′ 39.0″",
      "declinationDegree": 5,
      "declinationMinute": 13,
      "declinationSecond": 39,
      "starColor": "Blue/White"
    },
    {
      "latin": "Capricornus",
      "english": "Sea goat",
      "objectType": "Mythological",
      "area": 413.947,
      "mainStars": 9,
      "ra": "21h 47m 02.29s",
      "raHour": 21,
      "raMinute": 47,
      "raSecond": 2.29,
      "declination": "−16° 07′ 35.6″",
      "declinationDegree": -16,
      "declinationMinute": 7,
      "declinationSecond": 35.6,
      "starColor": "White"
    },
    {
      "latin": "Carina",
      "english": "Keel of Argonauts\' ship",
      "objectType": "Inanimate",
      "area": 494.184,
      "mainStars": 9,
      "ra": "06h 23m 57.09s",
      "raHour": 6,
      "raMinute": 23,
      "raSecond": 57.09,
      "declination": "−52° 41′ 44.6″",
      "declinationDegree": -52,
      "declinationMinute": 41,
      "declinationSecond": 44.6,
      "starColor": "Blue/White"
    },
    {
      "latin": "Cassiopeia",
      "english": "Queen of Ethiopia",
      "objectType": "Human",
      "area": 598.407,
      "mainStars": 5,
      "ra": "00h 56m 42.50s",
      "raHour": 0,
      "raMinute": 56,
      "raSecond": 42.5,
      "declination": "60° 43′ 00.3″",
      "declinationDegree": 60,
      "declinationMinute": 43,
      "declinationSecond": 0.3,
      "starColor": "Blue/White"
    },
    {
      "latin": "Centaurus",
      "english": "Centaur",
      "objectType": "Mythological",
      "area": 1060.422,
      "mainStars": 11,
      "ra": "14h 39m 40.90s",
      "raHour": 14,
      "raMinute": 39,
      "raSecond": 40.9,
      "declination": "−60° 50′ 06.5″",
      "declinationDegree": -60,
      "declinationMinute": 50,
      "declinationSecond": 6.5,
      "starColor": "Yellow"
    },
    {
      "latin": "Cepheus",
      "english": "King of Ethiopia",
      "objectType": "Human",
      "area": 587.787,
      "mainStars": 7,
      "ra": "21h 18m 34.58s",
      "raHour": 21,
      "raMinute": 18,
      "raSecond": 34.58,
      "declination": "62° 35′ 07.6″",
      "declinationDegree": 62,
      "declinationMinute": 35,
      "declinationSecond": 7.6,
      "starColor": "Blue"
    },
    {
      "latin": "Cetus",
      "english": "Sea monster (whale)",
      "objectType": "Mythological",
      "area": 1231.411,
      "mainStars": 14,
      "ra": "00h 43m 35.23s",
      "raHour": 0,
      "raMinute": 43,
      "raSecond": 35.23,
      "declination": "−17° 59′ 12.1″",
      "declinationDegree": -17,
      "declinationMinute": 59,
      "declinationSecond": 12.1,
      "starColor": "Orange"
    },
    {
      "latin": "Chamaeleon",
      "english": "Chameleon",
      "objectType": "Animal",
      "area": 131.592,
      "mainStars": 3,
      "ra": "08h 18m 31.27s",
      "raHour": 8,
      "raMinute": 18,
      "raSecond": 31.27,
      "declination": "−76° 55′ 11.9″",
      "declinationDegree": -76,
      "declinationMinute": 55,
      "declinationSecond": 11.9,
      "starColor": "Yellow"
    },
    {
      "latin": "Circinus",
      "english": "Compasses",
      "objectType": "Inanimate",
      "area": 93.353,
      "mainStars": 3,
      "ra": "14h 42m 30.69s",
      "raHour": 14,
      "raMinute": 42,
      "raSecond": 30.69,
      "declination": "−64° 58′ 28.5″",
      "declinationDegree": -64,
      "declinationMinute": 58,
      "declinationSecond": 28.5,
      "starColor": "Blue/White"
    },
    {
      "latin": "Columba",
      "english": "Dove",
      "objectType": "Animal",
      "area": 270.184,
      "mainStars": 5,
      "ra": "05h 39m 38.94s",
      "raHour": 5,
      "raMinute": 39,
      "raSecond": 38.94,
      "declination": "−34° 04′ 26.6″",
      "declinationDegree": -34,
      "declinationMinute": 4,
      "declinationSecond": 26.6,
      "starColor": "Red"
    },
    {
      "latin": "Coma Berenices",
      "english": "Berenice\'s hair",
      "objectType": "Inanimate",
      "area": 386.475,
      "mainStars": 3,
      "ra": "13h 11m 52.92s",
      "raHour": 13,
      "raMinute": 11,
      "raSecond": 52.92,
      "declination": "27° 52′ 33.7″",
      "declinationDegree": 27,
      "declinationMinute": 52,
      "declinationSecond": 33.7,
      "starColor": "Yellow"
    },
    {
      "latin": "Corona Australis",
      "english": "Southern crown",
      "objectType": "Inanimate",
      "area": 127.696,
      "mainStars": 6,
      "ra": "19h 10m 01.75s",
      "raHour": 19,
      "raMinute": 10,
      "raSecond": 1.75,
      "declination": "−39° 20′ 26.5″",
      "declinationDegree": -39,
      "declinationMinute": 20,
      "declinationSecond": 26.5,
      "starColor": "Blue"
    },
    {
      "latin": "Corona Borealis N",
      "english": "Northern crown",
      "objectType": "Inanimate",
      "area": 178.71,
      "mainStars": 8,
      "ra": "15h 34m 41.19s",
      "raHour": 15,
      "raMinute": 34,
      "raSecond": 41.19,
      "declination": "26° 42′ 53.7″",
      "declinationDegree": 26,
      "declinationMinute": 42,
      "declinationSecond": 53.7,
      "starColor": "White"
    },
    {
      "latin": "Corvus",
      "english": "Crow",
      "objectType": "Animal",
      "area": 183.801,
      "mainStars": 4,
      "ra": "12h 15m 48.47s",
      "raHour": 12,
      "raMinute": 15,
      "raSecond": 48.47,
      "declination": "−17° 32′ 31.1″",
      "declinationDegree": -17,
      "declinationMinute": 32,
      "declinationSecond": 31.1,
      "starColor": "Blue"
    },
    {
      "latin": "Crater",
      "english": "Cup",
      "objectType": "Inanimate",
      "area": 282.398,
      "mainStars": 4,
      "ra": "11h 19m 20.52s",
      "raHour": 11,
      "raMinute": 19,
      "raSecond": 20.52,
      "declination": "−14° 46′ 44.6″",
      "declinationDegree": -14,
      "declinationMinute": 46,
      "declinationSecond": 44.6,
      "starColor": "Orange"
    },
    {
      "latin": "Crux",
      "english": "Cross (southern)",
      "objectType": "Inanimate",
      "area": 68.447,
      "mainStars": 4,
      "ra": "12h 47m 43.32s",
      "raHour": 12,
      "raMinute": 47,
      "raSecond": 43.32,
      "declination": "−59° 41′ 19.4″",
      "declinationDegree": -59,
      "declinationMinute": 41,
      "declinationSecond": 19.4,
      "starColor": "Blue/White"
    },
    {
      "latin": "Cygnus",
      "english": "Swan",
      "objectType": "Animal",
      "area": 803.983,
      "mainStars": 9,
      "ra": "20h 41m 25.91s",
      "raHour": 20,
      "raMinute": 41,
      "raSecond": 25.91,
      "declination": "45° 16′ 49.2″",
      "declinationDegree": 45,
      "declinationMinute": 16,
      "declinationSecond": 49.2,
      "starColor": "Blue"
    },
    {
      "latin": "Delphinus",
      "english": "Porpoise",
      "objectType": "Animal",
      "area": 188.549,
      "mainStars": 5,
      "ra": "20h 37m 32.87s",
      "raHour": 20,
      "raMinute": 37,
      "raSecond": 32.87,
      "declination": "14° 35′ 42.7″",
      "declinationDegree": 14,
      "declinationMinute": 35,
      "declinationSecond": 42.7,
      "starColor": "Yellow"
    },
    {
      "latin": "Dorado",
      "english": "Swordfish",
      "objectType": "Animal",
      "area": 179.173,
      "mainStars": 3,
      "ra": "04h 33m 59.72s",
      "raHour": 4,
      "raMinute": 33,
      "raSecond": 59.72,
      "declination": "−55° 02′ 42.0″",
      "declinationDegree": -55,
      "declinationMinute": 2,
      "declinationSecond": 42,
      "starColor": "White"
    },
    {
      "latin": "Draco",
      "english": "Dragon",
      "objectType": "Mythological",
      "area": 1082.952,
      "mainStars": 14,
      "ra": "17h 56m 36.38s",
      "raHour": 17,
      "raMinute": 56,
      "raSecond": 36.38,
      "declination": "51° 29′ 20.2″",
      "declinationDegree": 51,
      "declinationMinute": 29,
      "declinationSecond": 20.2,
      "starColor": "Orange"
    },
    {
      "latin": "Equuleus",
      "english": "Little horse",
      "objectType": "Animal",
      "area": 71.641,
      "mainStars": 3,
      "ra": "21h 15m 49.40s",
      "raHour": 21,
      "raMinute": 15,
      "raSecond": 49.4,
      "declination": "05° 14′ 53.1″",
      "declinationDegree": 5,
      "declinationMinute": 14,
      "declinationSecond": 53.1,
      "starColor": "Yellow"
    },
    {
      "latin": "Eridanus",
      "english": "River",
      "objectType": "Inanimate",
      "area": 1137.919,
      "mainStars": 24,
      "ra": "01h 37m 42.75s",
      "raHour": 1,
      "raMinute": 37,
      "raSecond": 42.75,
      "declination": "−57° 14′ 12.0″",
      "declinationDegree": -57,
      "declinationMinute": 14,
      "declinationSecond": 12,
      "starColor": "Blue/White"
    },
    {
      "latin": "Fornax",
      "english": "Furnace",
      "objectType": "Inanimate",
      "area": 397.502,
      "mainStars": 2,
      "ra": "03h 12m 04.28s",
      "raHour": 3,
      "raMinute": 12,
      "raSecond": 4.28,
      "declination": "−28° 59′ 20.8″",
      "declinationDegree": -28,
      "declinationMinute": 59,
      "declinationSecond": 20.8,
      "starColor": "Yellow"
    },
    {
      "latin": "Gemini",
      "english": "Twins",
      "objectType": "Human",
      "area": 513.761,
      "mainStars": 8,
      "ra": "07h 45m 19.36s",
      "raHour": 7,
      "raMinute": 45,
      "raSecond": 19.36,
      "declination": "28° 01′ 34.7″",
      "declinationDegree": 28,
      "declinationMinute": 1,
      "declinationSecond": 34.7,
      "starColor": "Orange"
    },
    {
      "latin": "Grus",
      "english": "Crane",
      "objectType": "Animal",
      "area": 365.513,
      "mainStars": 8,
      "ra": "22h 08m 13.88s",
      "raHour": 22,
      "raMinute": 8,
      "raSecond": 13.88,
      "declination": "−46° 57′ 38.2″",
      "declinationDegree": -46,
      "declinationMinute": 57,
      "declinationSecond": 38.2,
      "starColor": "Blue/White"
    },
    {
      "latin": "Hercules",
      "english": "Hercules, son of Zeus",
      "objectType": "Human",
      "area": 1225.148,
      "mainStars": 14,
      "ra": "16h 30m 13.26s",
      "raHour": 16,
      "raMinute": 30,
      "raSecond": 13.26,
      "declination": "21° 29′ 22.7″",
      "declinationDegree": 32,
      "declinationMinute": 29,
      "declinationSecond": 22.7,
      "starColor": "Yellow"
    },
    {
      "latin": "Horologium",
      "english": "Clock",
      "objectType": "Inanimate",
      "area": 248.885,
      "mainStars": 6,
      "ra": "04h 14m 00.08s",
      "raHour": 4,
      "raMinute": 14,
      "raSecond": 0.08,
      "declination": "−42° 17′ 37.9″",
      "declinationDegree": -42,
      "declinationMinute": 17,
      "declinationSecond": 37.9,
      "starColor": "Red"
    },
    {
      "latin": "Hydra",
      "english": "Sea serpent",
      "objectType": "Mythological",
      "area": 1302.844,
      "mainStars": 17,
      "ra": "09h 27m 35.25s",
      "raHour": 9,
      "raMinute": 27,
      "raSecond": 35.25,
      "declination": "−08° 39′ 31.3″",
      "declinationDegree": -8,
      "declinationMinute": 39,
      "declinationSecond": 31.3,
      "starColor": "Orange"
    },
    {
      "latin": "Hydrus",
      "english": "Water snake",
      "objectType": "Mythological",
      "area": 243.035,
      "mainStars": 3,
      "ra": "00h 25m 39.20s",
      "raHour": 0,
      "raMinute": 25,
      "raSecond": 39.2,
      "declination": "−77° 15′ 18.1″",
      "declinationDegree": -77,
      "declinationMinute": 15,
      "declinationSecond": 18.1,
      "starColor": "Yellow"
    },
    {
      "latin": "Indus",
      "english": "Indian",
      "objectType": "Human",
      "area": 294.006,
      "mainStars": 3,
      "ra": "20h 37m 33.99s",
      "raHour": 20,
      "raMinute": 37,
      "raSecond": 33.99,
      "declination": "−47° 17′ 30.0″",
      "declinationDegree": -47,
      "declinationMinute": 17,
      "declinationSecond": 30,
      "starColor": "Red"
    },
    {
      "latin": "Lacerta",
      "english": "Lizard",
      "objectType": "Animal",
      "area": 200.688,
      "mainStars": 5,
      "ra": "22h 31m 17.38s",
      "raHour": 22,
      "raMinute": 31,
      "raSecond": 17.38,
      "declination": "50° 16′ 56.8″",
      "declinationDegree": 50,
      "declinationMinute": 16,
      "declinationSecond": 56.8,
      "starColor": "White"
    },
    {
      "latin": "Leo",
      "english": "Lion",
      "objectType": "Animal",
      "area": 946.964,
      "mainStars": 9,
      "ra": "10h 08m 22.46s",
      "raHour": 10,
      "raMinute": 8,
      "raSecond": 22.46,
      "declination": "11° 58′ 01.9″",
      "declinationDegree": 11,
      "declinationMinute": 58,
      "declinationSecond": 1.9,
      "starColor": "Blue"
    },
    {
      "latin": "Leo Minor",
      "english": "Little lion",
      "objectType": "Animal",
      "area": 231.956,
      "mainStars": 3,
      "ra": "10h 53m 18.64s",
      "raHour": 10,
      "raMinute": 53,
      "raSecond": 18.64,
      "declination": "34° 12′ 56.0″",
      "declinationDegree": 34,
      "declinationMinute": 12,
      "declinationSecond": 56,
      "starColor": "Red"
    },
    {
      "latin": "Lepus",
      "english": "Hare",
      "objectType": "Animal",
      "area": 290.291,
      "mainStars": 8,
      "ra": "05h 32m 43.81s",
      "raHour": 5,
      "raMinute": 32,
      "raSecond": 43.81,
      "declination": "−17° 49′ 20.3″",
      "declinationDegree": -17,
      "declinationMinute": 49,
      "declinationSecond": 20.3,
      "starColor": "Yellow"
    },
    {
      "latin": "Libra",
      "english": "Balance",
      "objectType": "Inanimate",
      "area": 538.052,
      "mainStars": 4,
      "ra": "15h 17m 00.47s",
      "raHour": 15,
      "raMinute": 17,
      "raSecond": 0.47,
      "declination": "−09° 22′ 58.3″",
      "declinationDegree": -9,
      "declinationMinute": 22,
      "declinationSecond": 58.3,
      "starColor": "Blue/White"
    },
    {
      "latin": "Lupus",
      "english": "Wolf",
      "objectType": "Animal",
      "area": 333.683,
      "mainStars": 9,
      "ra": "14h 41m 55.77s",
      "raHour": 14,
      "raMinute": 41,
      "raSecond": 55.77,
      "declination": "−47° 23′ 17.3″",
      "declinationDegree": -47,
      "declinationMinute": 23,
      "declinationSecond": 17.3,
      "starColor": "Blue/White"
    },
    {
      "latin": "Lynx",
      "english": "Lynx",
      "objectType": "Animal",
      "area": 545.386,
      "mainStars": 4,
      "ra": "09h 21m 03.46s",
      "raHour": 9,
      "raMinute": 21,
      "raSecond": 3.46,
      "declination": "34° 23′ 33.1″",
      "declinationDegree": 34,
      "declinationMinute": 23,
      "declinationSecond": 33.1,
      "starColor": "Orange"
    },
    {
      "latin": "Lyra",
      "english": "Lyre or harp",
      "objectType": "Inanimate",
      "area": 286.476,
      "mainStars": 5,
      "ra": "18h 36m 56.19s",
      "raHour": 18,
      "raMinute": 36,
      "raSecond": 56.19,
      "declination": "38° 46′ 58.8″",
      "declinationDegree": 38,
      "declinationMinute": 46,
      "declinationSecond": 58.8,
      "starColor": "Blue"
    },
    {
      "latin": "Mensa",
      "english": "Table mountain",
      "objectType": "Inanimate",
      "area": 153.484,
      "mainStars": 4,
      "ra": "06h 10m 14.20s",
      "raHour": 6,
      "raMinute": 10,
      "raSecond": 14.2,
      "declination": "−74° 45′ 09.1″",
      "declinationDegree": -74,
      "declinationMinute": 45,
      "declinationSecond": 9.1,
      "starColor": "Yellow"
    },
    {
      "latin": "Microscopium",
      "english": "Microscope",
      "objectType": "Inanimate",
      "area": 209.513,
      "mainStars": 5,
      "ra": "21h 01m 17.46s",
      "raHour": 21,
      "raMinute": 1,
      "raSecond": 17.46,
      "declination": "−32° 15′ 28.0″",
      "declinationDegree": -32,
      "declinationMinute": 15,
      "declinationSecond": 28,
      "starColor": "Yellow"
    },
    {
      "latin": "Monoceros",
      "english": "Unicorn",
      "objectType": "Mythological",
      "area": 481.569,
      "mainStars": 4,
      "ra": "07h 41m 14.88s",
      "raHour": 7,
      "raMinute": 41,
      "raSecond": 14.88,
      "declination": "−09° 33′ 03.9″",
      "declinationDegree": -9,
      "declinationMinute": 33,
      "declinationSecond": 3.9,
      "starColor": "Orange"
    },
    {
      "latin": "Musca",
      "english": "Fly",
      "objectType": "Animal",
      "area": 138.355,
      "mainStars": 6,
      "ra": "12h 37m 11.08s",
      "raHour": 12,
      "raMinute": 37,
      "raSecond": 11.08,
      "declination": "−69° 08′ 07.9″",
      "declinationDegree": -69,
      "declinationMinute": 8,
      "declinationSecond": 7.9,
      "starColor": "Blue/White"
    },
    {
      "latin": "Norma",
      "english": "Carpenter\'s Level",
      "objectType": "Inanimate",
      "area": 165.29,
      "mainStars": 4,
      "ra": "16h 19m 50.57s",
      "raHour": 16,
      "raMinute": 19,
      "raSecond": 50.57,
      "declination": "−50° 09′ 19.4″",
      "declinationDegree": -50,
      "declinationMinute": 9,
      "declinationSecond": 19.4,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Octans",
      "english": "Octant",
      "objectType": "Inanimate",
      "area": 291.045,
      "mainStars": 3,
      "ra": "21h 41m 28.47s",
      "raHour": 21,
      "raMinute": 41,
      "raSecond": 28.47,
      "declination": "−77° 23′ 22.1″",
      "declinationDegree": -77,
      "declinationMinute": 23,
      "declinationSecond": 22.1,
      "starColor": "Orange"
    },
    {
      "latin": "Ophiuchus",
      "english": "Holder of serpent",
      "objectType": "Human",
      "area": 948.34,
      "mainStars": 10,
      "ra": "17h 34m 56.00s",
      "raHour": 17,
      "raMinute": 34,
      "raSecond": 56,
      "declination": "12° 33′ 38.1″",
      "declinationDegree": 12,
      "declinationMinute": 33,
      "declinationSecond": 38.1,
      "starColor": "Blue/White"
    },
    {
      "latin": "Orion",
      "english": "Orion, the hunter",
      "objectType": "Human",
      "area": 594.12,
      "mainStars": 7,
      "ra": "05h 14m 32.27s",
      "raHour": 5,
      "raMinute": 14,
      "raSecond": 32.27,
      "declination": "−08° 12′ 05.9″",
      "declinationDegree": -8,
      "declinationMinute": 12,
      "declinationSecond": 5.9,
      "starColor": "Blue/White"
    },
    {
      "latin": "Pavo",
      "english": "Peacock",
      "objectType": "Animal",
      "area": 377.666,
      "mainStars": 7,
      "ra": "20h 25m 38.85s",
      "raHour": 20,
      "raMinute": 25,
      "raSecond": 38.85,
      "declination": "−56° 44′ 05.6″",
      "declinationDegree": -56,
      "declinationMinute": 44,
      "declinationSecond": 5.6,
      "starColor": "Blue"
    },
    {
      "latin": "Pegasus",
      "english": "Pegasus, the winged horse",
      "objectType": "Mythological",
      "area": 1120.794,
      "mainStars": 9,
      "ra": "21h 44m 11.14s",
      "raHour": 21,
      "raMinute": 44,
      "raSecond": 11.14,
      "declination": "09° 52′ 30.0″",
      "declinationDegree": 9,
      "declinationMinute": 52,
      "declinationSecond": 30,
      "starColor": "Orange"
    },
    {
      "latin": "Perseus",
      "english": "Perseus, hero who saved Andromeda",
      "objectType": "Human",
      "area": 614.997,
      "mainStars": 19,
      "ra": "03h 24m 19.35s",
      "raHour": 3,
      "raMinute": 24,
      "raSecond": 19.35,
      "declination": "49° 51′ 40.5″",
      "declinationDegree": 49,
      "declinationMinute": 51,
      "declinationSecond": 40.5,
      "starColor": "Yellow"
    },
    {
      "latin": "Phoenix",
      "english": "Phoenix",
      "objectType": "Mythological",
      "area": 469.319,
      "mainStars": 4,
      "ra": "00h 26m 16.87s",
      "raHour": 0,
      "raMinute": 26,
      "raSecond": 16.87,
      "declination": "−42° 18′ 18.4″",
      "declinationDegree": -42,
      "declinationMinute": 18,
      "declinationSecond": 18.4,
      "starColor": "Orange"
    },
    {
      "latin": "Pictor",
      "english": "Easel",
      "objectType": "Inanimate",
      "area": 246.739,
      "mainStars": 3,
      "ra": "06h 48m 11.54s",
      "raHour": 6,
      "raMinute": 48,
      "raSecond": 11.54,
      "declination": "−61° 56′ 31.1″",
      "declinationDegree": -61,
      "declinationMinute": 56,
      "declinationSecond": 31.1,
      "starColor": "White"
    },
    {
      "latin": "Pisces",
      "english": "Fishes",
      "objectType": "Animal",
      "area": 889.417,
      "mainStars": 18,
      "ra": "01h 31m 28.99s",
      "raHour": 1,
      "raMinute": 31,
      "raSecond": 28.99,
      "declination": "15° 20′ 45.0″",
      "declinationDegree": 15,
      "declinationMinute": 20,
      "declinationSecond": 45,
      "starColor": "Yellow"
    },
    {
      "latin": "Piscis Austrinis",
      "english": "Southern fish",
      "objectType": "Animal",
      "area": 245.375,
      "mainStars": 7,
      "ra": "22h 57m 38.83s",
      "raHour": 22,
      "raMinute": 57,
      "raSecond": 38.83,
      "declination": "−29° 37′ 18.6″",
      "declinationDegree": -29,
      "declinationMinute": 37,
      "declinationSecond": 18.6,
      "starColor": "Blue/White"
    },
    {
      "latin": "Puppis",
      "english": "Stern of the Argonauts\' ship",
      "objectType": "Inanimate",
      "area": 673.434,
      "mainStars": 9,
      "ra": "08h 03m 35.07s",
      "raHour": 8,
      "raMinute": 3,
      "raSecond": 35.07,
      "declination": "−40° 00′ 11.5″",
      "declinationDegree": -40,
      "declinationMinute": 0,
      "declinationSecond": 11.5,
      "starColor": "Blue/White"
    },
    {
      "latin": "Pyxis",
      "english": "Compass on the Argonauts\' ship",
      "objectType": "Inanimate",
      "area": 220.833,
      "mainStars": 3,
      "ra": "08h 43m 35.55s",
      "raHour": 8,
      "raMinute": 43,
      "raSecond": 35.55,
      "declination": "−33° 11′ 11.1″",
      "declinationDegree": -33,
      "declinationMinute": 11,
      "declinationSecond": 11.1,
      "starColor": "Blue/White"
    },
    {
      "latin": "Reticulum",
      "english": "Net",
      "objectType": "Inanimate",
      "area": 113.936,
      "mainStars": 4,
      "ra": "04h 14m 25.43s",
      "raHour": 4,
      "raMinute": 14,
      "raSecond": 25.43,
      "declination": "−62° 28′ 26.3″",
      "declinationDegree": -62,
      "declinationMinute": 28,
      "declinationSecond": 26.3,
      "starColor": "Yellow"
    },
    {
      "latin": "Sagitta",
      "english": "Arrow",
      "objectType": "Inanimate",
      "area": 79.932,
      "mainStars": 4,
      "ra": "19h 58m 45.39s",
      "raHour": 19,
      "raMinute": 58,
      "raSecond": 45.39,
      "declination": "19° 29′ 31.5″",
      "declinationDegree": 19,
      "declinationMinute": 29,
      "declinationSecond": 31.5,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Sagittarius",
      "english": "Archer",
      "objectType": "Human",
      "area": 867.432,
      "mainStars": 12,
      "ra": "18h 24m 10.35s",
      "raHour": 18,
      "raMinute": 24,
      "raSecond": 10.35,
      "declination": "−34° 23′ 03.5″",
      "declinationDegree": -34,
      "declinationMinute": 23,
      "declinationSecond": 3.5,
      "starColor": "Blue"
    },
    {
      "latin": "Scorpius",
      "english": "Scorpion",
      "objectType": "Animal",
      "area": 496.783,
      "mainStars": 18,
      "ra": "16h 29m 24.47s",
      "raHour": 16,
      "raMinute": 29,
      "raSecond": 24.47,
      "declination": "−26° 25′ 55.0″",
      "declinationDegree": -26,
      "declinationMinute": 25,
      "declinationSecond": 55,
      "starColor": "Red"
    },
    {
      "latin": "Sculptor",
      "english": "Sculptor\'s tools",
      "objectType": "Inanimate",
      "area": 474.764,
      "mainStars": 4,
      "ra": "00h 58m 36.35s",
      "raHour": 0,
      "raMinute": 58,
      "raSecond": 36.35,
      "declination": "−29° 21′ 26.9″",
      "declinationDegree": -29,
      "declinationMinute": 21,
      "declinationSecond": 26.9,
      "starColor": "Blue"
    },
    {
      "latin": "Scutum",
      "english": "Shield",
      "objectType": "Inanimate",
      "area": 109.114,
      "mainStars": 2,
      "ra": "18h 35m 12.44s",
      "raHour": 18,
      "raMinute": 35,
      "raSecond": 12.44,
      "declination": "−08° 14′ 35.9″",
      "declinationDegree": -8,
      "declinationMinute": 14,
      "declinationSecond": 35.9,
      "starColor": "Orange"
    },
    {
      "latin": "Serpens",
      "english": "Serpent",
      "objectType": "Animal",
      "area": 636.928,
      "mainStars": 11,
      "ra": "15h 44m 16.00s",
      "raHour": 15,
      "raMinute": 44,
      "raSecond": 16,
      "declination": "06° 25′ 31.9″",
      "declinationDegree": 6,
      "declinationMinute": 25,
      "declinationSecond": 31.9,
      "starColor": "Orange/Red"
    },
    {
      "latin": "Sextans",
      "english": "Sextant",
      "objectType": "Inanimate",
      "area": 313.515,
      "mainStars": 3,
      "ra": "10h 07m 56.30s",
      "raHour": 10,
      "raMinute": 7,
      "raSecond": 56.3,
      "declination": "−00° 22′ 17.9″",
      "declinationDegree": 0,
      "declinationMinute": 22,
      "declinationSecond": 17.9,
      "starColor": "Blue/White"
    },
    {
      "latin": "Taurus",
      "english": "Bull",
      "objectType": "Animal",
      "area": 797.249,
      "mainStars": 19,
      "ra": "04h 35m 55.20s",
      "raHour": 4,
      "raMinute": 35,
      "raSecond": 55.2,
      "declination": "16° 30′ 35.1″",
      "declinationDegree": 16,
      "declinationMinute": 30,
      "declinationSecond": 35.1,
      "starColor": "Orange"
    },
    {
      "latin": "Telescopium",
      "english": "Telescope",
      "objectType": "Inanimate",
      "area": 251.512,
      "mainStars": 2,
      "ra": "18h 26m 58.43s",
      "raHour": 18,
      "raMinute": 26,
      "raSecond": 58.43,
      "declination": "−45° 58′ 06.0″",
      "declinationDegree": -45,
      "declinationMinute": 58,
      "declinationSecond": 6,
      "starColor": "Blue"
    },
    {
      "latin": "Triangulum",
      "english": "Triangle",
      "objectType": "Inanimate",
      "area": 131.847,
      "mainStars": 3,
      "ra": "02h 09m 32.52s",
      "raHour": 2,
      "raMinute": 9,
      "raSecond": 32.52,
      "declination": "34° 59′ 14.6″",
      "declinationDegree": 34,
      "declinationMinute": 59,
      "declinationSecond": 14.6,
      "starColor": "Blue/White"
    },
    {
      "latin": "Triangulum Australe",
      "english": "Southern triangle",
      "objectType": "Inanimate",
      "area": 109.978,
      "mainStars": 3,
      "ra": "16h 48m 39.87s",
      "raHour": 16,
      "raMinute": 48,
      "raSecond": 39.87,
      "declination": "−69° 01′ 39.5″",
      "declinationDegree": -69,
      "declinationMinute": 1,
      "declinationSecond": 39.5,
      "starColor": "Red"
    },
    {
      "latin": "Tucana",
      "english": "Toucan",
      "objectType": "Animal",
      "area": 294.557,
      "mainStars": 3,
      "ra": "22h 18m 30.18s",
      "raHour": 22,
      "raMinute": 18,
      "raSecond": 30.18,
      "declination": "−60° 15′ 34.2″",
      "declinationDegree": -60,
      "declinationMinute": 15,
      "declinationSecond": 34.2,
      "starColor": "Orange"
    },
    {
      "latin": "Ursa Major",
      "english": "Big bear",
      "objectType": "Animal",
      "area": 1279.66,
      "mainStars": 7,
      "ra": "12h 54m 01.63s",
      "raHour": 12,
      "raMinute": 54,
      "raSecond": 1.63,
      "declination": "55° 57′ 35.4″",
      "declinationDegree": 55,
      "declinationMinute": 57,
      "declinationSecond": 35.4,
      "starColor": "Blue/White"
    },
    {
      "latin": "Ursa Minor",
      "english": "Little bear",
      "objectType": "Animal",
      "area": 255.864,
      "mainStars": 7,
      "ra": "02h 31m 47.08s",
      "raHour": 2,
      "raMinute": 31,
      "raSecond": 47.08,
      "declination": "89° 15′ 50.9″",
      "declinationDegree": 89,
      "declinationMinute": 50,
      "declinationSecond": 50.9,
      "starColor": "Yellow"
    },
    {
      "latin": "Vela",
      "english": "Sail of the Argonauts\' ship",
      "objectType": "Inanimate",
      "area": 499.649,
      "mainStars": 5,
      "ra": "08h 09m 31.96s",
      "raHour": 8,
      "raMinute": 9,
      "raSecond": 31.96,
      "declination": "−47° 20′ 11.8″",
      "declinationDegree": -47,
      "declinationMinute": 20,
      "declinationSecond": 11.8,
      "starColor": "Blue"
    },
    {
      "latin": "Virgo",
      "english": "Virgin",
      "objectType": "Human",
      "area": 1294.428,
      "mainStars": 9,
      "ra": "13h 25m 11.60s",
      "raHour": 13,
      "raMinute": 25,
      "raSecond": 11.6,
      "declination": "−11° 09′ 40.5″",
      "declinationDegree": -11,
      "declinationMinute": 9,
      "declinationSecond": 40.5,
      "starColor": "Blue/White"
    },
    {
      "latin": "Volans",
      "english": "Flying fish",
      "objectType": "Animal",
      "area": 141.354,
      "mainStars": 6,
      "ra": "07h 08m 44.82s",
      "raHour": 7,
      "raMinute": 8,
      "raSecond": 44.82,
      "declination": "−70° 29′ 57.1″",
      "declinationDegree": -70,
      "declinationMinute": 29,
      "declinationSecond": 57.1,
      "starColor": "Orange"
    },
    {
      "latin": "Vulpecula",
      "english": "Fox",
      "objectType": "Animal",
      "area": 268.165,
      "mainStars": 5,
      "ra": "19h 28m 42.41s",
      "raHour": 19,
      "raMinute": 28,
      "raSecond": 42.41,
      "declination": "24° 39′ 54.6″",
      "declinationDegree": 24,
      "declinationMinute": 39,
      "declinationSecond": 54.6,
      "starColor": "Red"
    }
  ]`;

  function constellations() {
      return JSON.parse(data);
  }